openapi: 3.0.0
info:
  title: Controle de Contas API
  version: 1.0.0
  description: API para organização de dívidas, fontes e parcelas pessoais

servers:
  - url: http://localhost:3000

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

tags:
  - name: Users
    description: Operações relacionadas a usuários
  - name: Debts
    description: Operações com dívidas
  - name: Installments
    description: Parcelas de dívidas

paths:
  /api/users/register:
    post:
      tags:
        - Users
      summary: Registra um novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        201:
          description: Usuário criado com sucesso
        400:
          description: Dados inválidos

  /api/users/login:
    post:
      tags:
        - Users
      summary: Login e retorno do token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Token JWT retornado
        401:
          description: Credenciais inválidas

  /api/users/me:
    get:
      tags:
        - Users
      summary: Retorna dados do usuário autenticado
      security:
        - bearerAuth: []
      responses:
        200:
          description: Dados do usuário retornados com sucesso
        401:
          description: Token inválido ou ausente

    /api/debts:
    get:
      summary: Lista todas as dívidas do usuário autenticado
      tags: [Debts]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Lista de dívidas
        401:
          description: Token inválido ou ausente

    post:
      summary: Cria uma nova dívida
      tags: [Debts]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - description
                - debtSourceId
              properties:
                description:
                  type: string
                debtSourceId:
                  type: string
      responses:
        201:
          description: Dívida criada com sucesso
        400:
          description: Dados inválidos

  /api/debts/{id}:
    get:
      summary: Retorna uma dívida específica
      tags: [Debts]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Detalhes da dívida
        404:
          description: Dívida não encontrada

    put:
      summary: Atualiza uma dívida
      tags: [Debts]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
      responses:
        200:
          description: Dívida atualizada
        400:
          description: Dados inválidos

    delete:
      summary: Remove uma dívida
      tags: [Debts]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        204:
          description: Dívida removida
        404:
          description: Dívida não encontrada

  /api/installments:
    post:
      summary: Cria uma nova parcela para uma dívida
      tags: [Installments]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - amount
                - month
                - year
                - debtId
              properties:
                amount:
                  type: number
                month:
                  type: integer
                year:
                  type: integer
                type:
                  type: string
                status:
                  type: string
                  enum: [PENDING, PAID]
                debtId:
                  type: string
      responses:
        201:
          description: Parcela criada
        400:
          description: Dados inválidos

  /api/installments/{debtId}:
     get:
      summary: Lista as parcelas de uma dívida
      tags: [Installments]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: debtId
          required: true
          schema:
            type: string
      responses:
        200:
          description: Lista de parcelas
        404:
          description: Dívida não encontrada

     get:
      summary: Lista as parcelas de uma dívida
      tags: [Installments]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: debtId
          required: true
          schema:
            type: string
      responses:
        200:
          description: Lista de parcelas
        404:
          description: Dívida não encontrada
