services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: alisson
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: controle_contas
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://alisson:secret123@postgres:5432/controle_contas
    volumes:
      - .:/workspaces/personal-finance-app
    command: tail -f /dev/null

volumes:
  pgdata:
