services:
  postgres:
    image: postgres:16
    container_name: postgres_personal-finance-app
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  backend_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_personal-finance-app
    depends_on:
      - postgres
    ports:
      - '3001:3001'
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - .:/workspaces/personal-finance-app
    command: tail -f /dev/null

volumes:
  pgdata:
